apiVersion: v1
kind: Service
metadata:
  name: {{ include "modern-web.fullname" . }}
  labels:
    {{- include "modern-web.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "modern-web.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP