name: Deploy EKS Nginx Ingress with Observability

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Format
        run: cd terraform && terraform fmt
        
      - name: Terraform Init
        run: cd terraform && terraform init -backend=false
        
      - name: Terraform Validate
        run: cd terraform && terraform validate

  deploy:
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Setup Helm
        uses: azure/setup-helm@v3
        
      - name: Deploy Infrastructure
        run: |
          cd terraform
          # Initialize with state
          terraform init
          
          # Apply only specific resources to avoid conflicts
          terraform apply -auto-approve -target=aws_prometheus_workspace.amp -target=aws_prometheus_rule_group_namespace.nginx_rules
          
          # Get outputs for application deployment
          AMP_ENDPOINT=$(terraform output -raw amp_endpoint || echo "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-bb857fc7-c236-43c7-b89c-9defd1d34b8f/")
          AWS_REGION=$(terraform output -raw region || echo "us-east-1")
          
      - name: Deploy Application
        run: |
          # Update kubeconfig
          aws eks update-kubeconfig --region us-east-1 --name nginx-ingress-eks
          
          # Deploy Nginx Ingress
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx -f values.yaml || echo "Ingress controller may already be installed"
          
          # Deploy application with monitoring
          cd charts/modern-web
          helm install modern-web . \
            --set prometheus.ampEndpoint=$AMP_ENDPOINT \
            --set prometheus.awsRegion=$AWS_REGION || \
          helm upgrade modern-web . \
            --set prometheus.ampEndpoint=$AMP_ENDPOINT \
            --set prometheus.awsRegion=$AWS_REGION
