name: Deploy EKS Nginx Ingress with Observability

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Format
        run: cd terraform && terraform fmt
        
      - name: Terraform Init
        run: cd terraform && terraform init -backend=false
        
      - name: Terraform Validate
        run: cd terraform && terraform validate

  deploy:
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Setup Helm
        uses: azure/setup-helm@v3
        
      - name: Terraform Import
        run: |
          cd terraform
          # Import existing resources
          terraform import aws_iam_role.grafana grafana-role
          terraform import aws_iam_policy.grafana_amp_access arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):policy/GrafanaAMPAccess
          terraform import aws_iam_policy.prometheus_ingest arn:aws:iam::$(aws sts get-caller-identity --query Account --output text):policy/AMPIngestPolicy
          # Continue with apply
          terraform apply -auto-approve
          
      - name: Deploy Application
        run: |
          # Update kubeconfig
          aws eks update-kubeconfig --region us-east-1 --name nginx-ingress-eks
          # Deploy Nginx Ingress and application
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx -f values.yaml
          # Get AMP endpoint and role ARN
          AMP_ENDPOINT=$(cd terraform && terraform output -raw amp_endpoint)
          AMP_INGEST_ROLE_ARN=$(cd terraform && terraform output -raw prometheus_ingest_role_arn)
          AWS_REGION=$(cd terraform && terraform output -raw region)
          # Install application with monitoring
          helm install modern-web ./charts/modern-web \
            --set prometheus.ampEndpoint=$AMP_ENDPOINT \
            --set prometheus.ampIngestRoleArn=$AMP_INGEST_ROLE_ARN \
            --set prometheus.awsRegion=$AWS_REGION